### ISSUE TITLE
Error: Cannot find module 'ref'

### ISSUE THREAD

**Issue by mkress** [miroof/node-virtual-gamepads#53] opened 2017-09-03 07:53 UTC
Installed on Retropie 4.2.18 on Raspberry Pi 2 (with Raspbian Jessie) I get following error on manually start.
I changed config.json to Port 8098 - cause on port 80 I am running an apache-php-server.

on manually start I get:

`pi@raspberrypi /opt/retropie/supplementary/virtualgamepad $ sudo node main.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'ref'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/retropie/supplementary/virtualgamepad/lib/uinput_structs.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
`

I had to manually install ref
/opt/retropie/supplementary/virtualgamepad/node_modules $ sudo npm install ref

after that node/pm2 could start the virtual gamepad on my custom port 8089 (but it has nothing to do with the custom port) - I think the package.json should also include "ref" as dependency.

Thanks for this great extension!!!
best regards from Germany
Markus

**Comment by robsdedude** [comment] 2017-09-10 16:56
By installing `ref-array` which has the dependency `ref`, `ref` will be installed automatically. I just set up a new installation of node virtual gampeads and I couldn't reproduce this error (working on an x64 machine instead of an arm like the rpi2).

Please provide me with the node and npm versions you're using. Raspbian tends to deliver //really// old verions:
 - run `node -v` and `sudo node -v` to get the node version
 - run `npm -v` and `sudo npm -v` to get the npm version

**Comment by mkress** [comment] 2017-09-10 17:05
pi@raspberrypi ~ $ node -v
v4.8.4
pi@raspberrypi ~ $ sudo node -v
v4.8.4
pi@raspberrypi ~ $

pi@raspberrypi ~ $ npm -v
2.15.11
pi@raspberrypi ~ $ sudo npm -v
2.15.11
pi@raspberrypi ~ $


Seems to be really very old...

**Comment by robsdedude** [comment] 2017-09-10 18:51
This might be the problem. Can you try to update node (e.g. using [`n`](https://github.com/tj/n)), remove the installation, remove your manual `ref` installation, and reinstall node virtual gamepads?

**Comment by robsdedude** [comment] 2017-10-28 18:19
I'm closing this for now. Feel free to reopen it if needed.

**Closed by robsdedude** 2017-10-28 18:19 UTC
Labels: awaiting reply
