### ISSUE TITLE
i run sudo node main.js

### ISSUE THREAD

**Issue by asifagaria** [miroof/node-virtual-gamepads#60] opened 2018-09-06 12:24 UTC
giving errors

info: diedAfter: 427
info: earlyDeathCount: 3
error: Died too often too fast.
error: server.js has exited (gave up to restart)

**Comment by robsdedude** [comment] 2018-09-06 21:49
Is there more log output? I don't see the actual error. I just introduced a error in the code to test the output. And my console gives something like this:

```
$ sudo $(which node) main.js 

/mnt/D_Data/code/git/robsdedude/node-virtual-gamepads/server.js:140
    throw "BAM";
    ^
BAM
2018-09-06T23:45:57.713 - info: diedAfter: 329
2018-09-06T23:45:57.714 - info: earlyDeathCount: 1
2018-09-06T23:45:57.718 - error: Forever restarting script for 1 time

/mnt/D_Data/code/git/robsdedude/node-virtual-gamepads/server.js:140
    throw "BAM";
    ^
BAM
2018-09-06T23:45:58.055 - info: diedAfter: 338
2018-09-06T23:45:58.055 - info: earlyDeathCount: 2
2018-09-06T23:45:58.058 - error: Forever restarting script for 2 time

/mnt/D_Data/code/git/robsdedude/node-virtual-gamepads/server.js:140
    throw "BAM";
    ^
BAM
2018-09-06T23:45:58.392 - info: diedAfter: 334
2018-09-06T23:45:58.392 - info: earlyDeathCount: 3
2018-09-06T23:45:58.392 - error: Died too often too fast.
2018-09-06T23:45:58.413 - info: received exit
```

**Comment by asifagaria** [comment] 2018-09-07 17:11
still error

**Comment by robsdedude** [comment] 2018-09-08 06:44
I didn't want you to execute the command the way I did. What I was mainly interested is, is the while error message. The should be more than you posted. Your snippet doesn't tell anything about the actual error.

**Comment by asifagaria** [comment] 2018-09-09 05:04
showing this error

/var/www/html/retroarch/node-virtual-gamepads/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/out/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/out/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/default/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/compiled/11.0.0-pre/linux/x64/ioctl.node
    at bindings (/var/www/html/retroarch/node-virtual-gamepads/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/index.js:1:94)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/www/html/retroarch/node-virtual-gamepads/app/virtual_gamepad.js:13:11)
info: diedAfter: 420
info: earlyDeathCount: 1
error: Forever restarting script for 1 time
/var/www/html/retroarch/node-virtual-gamepads/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/out/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/out/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/default/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/compiled/11.0.0-pre/linux/x64/ioctl.node
    at bindings (/var/www/html/retroarch/node-virtual-gamepads/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/index.js:1:94)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/www/html/retroarch/node-virtual-gamepads/app/virtual_gamepad.js:13:11)
info: diedAfter: 481
info: earlyDeathCount: 2
error: Forever restarting script for 2 time
/var/www/html/retroarch/node-virtual-gamepads/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/out/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/Debug/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/out/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/Release/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/build/default/ioctl.node
 → /var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/compiled/11.0.0-pre/linux/x64/ioctl.node
    at bindings (/var/www/html/retroarch/node-virtual-gamepads/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/var/www/html/retroarch/node-virtual-gamepads/node_modules/ioctl/index.js:1:94)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/www/html/retroarch/node-virtual-gamepads/app/virtual_gamepad.js:13:11)
info: diedAfter: 398
info: earlyDeathCount: 3
error: Died too often too fast.
error: server.js has exited (gave up to restart)

**Comment by robsdedude** [comment] 2018-09-09 21:26
Ah. This is way more helpful. Looks like you didn't install the dependies correctly. You can try to run `npm rebuild` inside `/var/www/html/retroarch/node-virtual-gamepads`.

I'll close the issue as it's not a bug. But feel free to ask further questions.

**Closed by robsdedude** 2018-09-09 21:26 UTC
Labels: awaiting reply, help wanted
